### ISSUE TITLE
console.log value assigned to temporary parameter

### ISSUE THREAD

**Issue by gsivaprabu** [unknownuser88/consolewrap#10]
Hi,

Can you modify the console.log('name',name); to  console.log('name',**nameVal = name**); like that its easy to debug for developers.

We can access the ***nameVal*** in console for calling and binding is easy.

![github](https://cloud.githubusercontent.com/assets/2444608/23364446/1f56d248-fd25-11e6-8bff-4167c672d4e1.jpg)

regards,

@gsivaprabu

**Comment by gsivaprabu** [comment]
FYI :- @ArnaudRinquin  @bfred-it  @unknownuser88

**Comment by unknownuser88** [comment]
In version 0.1.0 you can change settings like this `"consoleStr": "\"console.log('%s', %s);\" % (text, variable + 'Val = ' + variable)"` or whatever you want

**Comment by gsivaprabu** [comment]
@unknownuser88  Hi where i need to changes this one. If i installed v0.0.8 only installed

**Comment by bfred-it** [comment]
@gsivaprabu install the new one

**Comment by unknownuser88** [comment]
just remove plugin and install latest version
