### ISSUE TITLE
Paste to previous line?

### ISSUE THREAD

**Issue by Vindexus** [unknownuser88/consolewrap#11]
Is there a way to put the console.log above the currently selected text?

**Comment by unknownuser88** [comment]
I think it will be in the next version

**Comment by Vindexus** [comment]
Honestly not as needed as I thought. Could maybe useful as another shortcut like ctrl+shift+uparrow+q?

Thanks for this project though, loving it.

**Comment by unknownuser88** [comment]
in version 0.1.0 you can use `ctrl+shift+alt+q` to insert before selection

**Comment by Vindexus** [comment]
That's awesome, thanks a lot!
