### ISSUE TITLE
Setting for semicolon?

### ISSUE THREAD

**Issue by bijoythomas** [unknownuser88/consolewrap#18]
Is it possible to add a setting for semicolon insertion too?

**Comment by unknownuser88** [comment]
Do you mean insert semicolon on the end or no ?

**Comment by bijoythomas** [comment]
Yes. We are moving away from having semi-colons in our JS files and having a setting like this will be really helpful.

**Comment by unknownuser88** [comment]
Ok I'll add this in next version

**Comment by bijoythomas** [comment]
Thanks. I created a PR for this.
