### ISSUE TITLE
Somthing wrong with settings

### ISSUE THREAD

**Issue by qaraluch** [unknownuser88/consolewrap#21]
Settings are grayed out:

![screenshot_1](https://cloud.githubusercontent.com/assets/6145570/24588192/d8872714-17c3-11e7-8f7c-380a87e37e50.png)

Platform: Windows 7.

**Comment by unknownuser88** [comment]
Sublime text 2 or 3?

**Comment by qaraluch** [comment]
ST3

**Comment by unknownuser88** [comment]
Any error in sublime's console (ctrl+`)?

**Comment by qaraluch** [comment]
No, just:
[Console Wrap] ****************************** loaded ******************************

**Comment by qaraluch** [comment]
After Console Wrap package installation all ST settings files are in ".sublime" dir but should be in package dir itself, I guess?

**Comment by unknownuser88** [comment]
.sublime works fine I forgot to import some classes

**Comment by qaraluch** [comment]
Still something not right with settings: 
![screenshot_1](https://cloud.githubusercontent.com/assets/6145570/24645952/6312567c-191a-11e7-96ff-d764613fbf6a.png)

Platform: Win7; ST3; version of CW: 1.04; no error indications.

**Comment by unknownuser88** [comment]
I change path after rename will be fixed in version v1.0.5
