### ISSUE TITLE
Multiple comment slashes for duplicate logs

### ISSUE THREAD

**Issue by webdevnerdstuff** [unknownuser88/consolewrap#23]
ST3: Build 3126
OS: Win7

I'm not sure if this is by design or not. 

If you have multiple console logs with the same thing/value being logged it adds "//" the same number count of the identical logs. This it turn affects when you "_Remove commented logs_" or "_Remove All logs_" by only removing the first one preceding the log.  It does this for both JS and PHP (haven't tested Python). Otherwise everything works good.

### Before "Comment All logs"
console.log("foo");
console.log("bar");
console.log(foo);
console.log(bar);
console.log(foo);
console.log("bar");
console.log("bar");

### After "Comment All logs"
// // // console.log("bar");
// // console.log(foo);
// console.log(bar);
// // console.log(foo);
// // // console.log("bar");
// // // console.log("bar");

### After "Remove Commented logs" & "Remove All logs

// // 
// 

// 
// // 
// //

**Comment by unknownuser88** [comment]
Oops, yep, that's bad, I'm trying to fix it
