### ISSUE TITLE
Indent using space

### ISSUE THREAD

**Issue by ShineOfFire** [unknownuser88/consolewrap#24]
Hello, i think for a new update you can add a setting for indent spaces, when we use your plugin :)

**Comment by unknownuser88** [comment]
plugin use tabs if your string indented with tab otherwise it use spaces
![screenshot from 2017-06-29 15-31-23](https://user-images.githubusercontent.com/2427559/27685655-3b2e7096-5ce0-11e7-9c67-08d8f6acd916.png)
