### ISSUE TITLE
Console Wrap: not work in this file type source.js.dom

### ISSUE THREAD

**Issue by zymr-keshav** [unknownuser88/consolewrap#26]
- macOS v 10.1.25 
- Sublime Text 3 build 3126

Installed Console Wrap plugin and it was working fine till now but suddenly it stopped working (using _Control + Shift + q_ keyboard shortcut ) and it gives error in gutter 

> Console Wrap: not work in this file type source.js.dom

my file extension is  *.js* and using es6 syntax..

can someone shed light how to fix that? I have restarted the ST3 but no affect.

**Comment by unknownuser88** [comment]
as I can see your file extension is .js.dot 
try to open settings (Preferences->Package Settings->Console Wrap->setting) and add that extension to your user settings like this

```
"fileTypeMap": {
	"text.html.vue": "js",
	"source.ts": "js",
	"source.js.dom": "js", // <-- 
	"source.tsx": "js",
	"source.coffee": "js",
	"text.html.basic": "js",
	"text.html.blade": "js",
	"text.html.twig": "js"
}
```

**Comment by zymr-keshav** [comment]
Thank you for the quick response.it has been fixed now. But my file does does not have `.js.dot` it was working fine earlier.

**Comment by unknownuser88** [comment]
plugin detect language from scope not from extension (because in php file can be script tag with javascript) if you put cursor in place you want to use plugin and press ctrl+alt+shift+p (show_scope_name) it show scope name

**Comment by zymr-keshav** [comment]
thanks for the tips. Yes this is showing `source.js.dom` BUT why so? my file extension is *.js*

**Comment by unknownuser88** [comment]
Maybe it some custom syntax like jsx or something like that
