### ISSUE TITLE
Support Jasmine files

### ISSUE THREAD

**Issue by tarjei** [unknownuser88/consolewrap#27]
Hi, somehow the Jasmine plugin defines it's own scope. Is there some way for this plugin to support .spec.js files that the Jasmine plugin (or others like it) has defined within it's purview?

**Comment by unknownuser88** [comment]
Hello, please provide me Jasmine plugin link and send me it's scope name (put cursor then in top menu Tools>Developer>Show Scope Name)

**Comment by tarjei** [comment]
Hi, jupp. Heres the output:
Scope:
source.js.jasmine
 meta.block.js
 string.regexp.js

Plugin link: https://github.com/NicoSantangelo/sublime-jasmine


Thanks for the quick reply, sorry you had to wait for the response.

**Comment by unknownuser88** [comment]
Just add it to fileTypeMap like this "source.js.jasmine": "js" 

preferences>Package settings>Console Wrap>settings and add this

```
 "fileTypeMap" : {
		"text.html.vue": "js", 
		"source.ts": "js",
		"source.js.jasmine": "js", // <-- add this
		"source.tsx": "js",
		"source.coffee": "js",
		"text.html.basic": "js",
		"text.html.blade": "js",
		"text.html.twig": "js"
	}
```
