### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by recs182** [unknownuser88/consolewrap#28]
It would be even nicer if we could be able to customize console's color in JS, like this below
![colors](https://user-images.githubusercontent.com/5971123/41944835-57c88f30-7980-11e8-8f1f-2d7961fda970.PNG)
`console.log('%cERR example example example', 'background:green;color:white;', err);`

**Comment by unknownuser88** [comment]
You can set it from settings
`"consoleStr"   : "%c{title}, 'background:green;color:white;', {variable}"`
![image](https://user-images.githubusercontent.com/2427559/42156594-86806002-7dfc-11e8-8506-2442f084fbf8.png)

**Comment by recs182** [comment]
Oh, sorry for bother them... the settings wasn't opening since I didn't update the package, so I didn't know of this. Thanks for the help.
