### ISSUE TITLE
Feature Request Console wrap for vscode support ?

### ISSUE THREAD

**Issue by sivaprabug** [unknownuser88/consolewrap#29]
For **Feature Request** possible to support Console wrap for vscode ?

**Comment by unknownuser88** [comment]
Hi, try to search in vscode marketplace 
here is some similar packages 
[Log Wrapper](https://marketplace.visualstudio.com/items?itemName=chrisvltn.log-wrapper-for-vscode)
[Console Wrapper](https://marketplace.visualstudio.com/items?itemName=fabiodam.vscode-console-wrapper)

**Comment by gsivaprabu** [comment]
@unknownuser88  but not this much
