### ISSUE TITLE
Could it automatically select the string that it outputs

### ISSUE THREAD

**Issue by eorroe** [unknownuser88/consolewrap#5]
It'd save a couple keystrokes if it'd automatically selected the string after it writes code

**Comment by unknownuser88** [comment]
Can you please give me more information?
In which case it will be useful?

**Comment by eorroe** [comment]
This is how it currently works:

![now](https://cloud.githubusercontent.com/assets/6982605/23629771/b3a0fa08-0286-11e7-8723-a9b53f57b9cf.gif)

I prefer if it automatically selected the wrapped text:
![should](https://cloud.githubusercontent.com/assets/6982605/23629812/dec8d746-0286-11e7-8712-c41b52927183.gif)

**Probably should select both the text and variable, and if possible make it where I can cycle through it by pressing tab**

**Comment by unknownuser88** [comment]
Sorry but I don't think that the plugin should do this 
but you can use macro to get this effect 

I think the following macro do the trick
```
[
	{
		"args": null,
		"command": "consolewrap"
	},
	{
		"args":
		{
			"by": "characters",
			"forward": false
		},
		"command": "move"
	},
	{
		"args":
		{
			"by": "characters",
			"forward": false
		},
		"command": "move"
	},
	{
		"args":
		{
			"by": "words",
			"extend": true,
			"forward": false
		},
		"command": "move"
	}
]
```

**Comment by eorroe** [comment]
Why shouldn't it select it? Why still being able to loop through?

Or what about selects the method loops through when recalling and then tabbing selects the wrapped text. Or is this complicated?
