### ISSUE TITLE
customizable

### ISSUE THREAD

**Issue by arfa** [unknownuser88/consolewrap#6]
Is it possible to make it customizable ?

So it can be one of the following options

`console.log`
`console.debug`
`console.info`
`console.warn`
`console.error`

**Comment by ianmaddox** [comment]
Great plugin. This feature would make it even better!

**Comment by eorroe** [comment]
Yea if the whole plugin was a way to loop through a whole set of wrappings per scope this would be awesome. I'm sure the installs would go high up.

Meaning I could define per scope what type of wrappings I'd like to loop through for the selected text or whats in the clipboard as it works now, this would be super awesome.

**Comment by unknownuser88** [comment]
done in version 0.0.8
